### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mananapr** [mananapr/parachute-panic#1]
## TODO
- [x] Learn JavaFX
- [x] Wind Mechanics
- [x] Bosses
- [x] Randomization
- [x] Sound 
- [x] Multithreading
- [x] Loose life without Parachute
- [x] Serialization of High Score
- [x] Retain score and life with subsequent levels
- [x] Redirect to main menu after death or completion of final level
- [x] Fix position of Score label
- [x] Make a level with black hole
